name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: Deploy on gh-pages if mention
    if: startsWith(github.event.commits[0].message, 'ext')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package extension
      run: |
        zip -r extension.zip . -x "*.git*"

    - name: Publish extension
      uses: chrome-extension-deploy@v1
      with:
        client_id: ${{ secrets.CHROME_CLIENT_ID }}
        client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh_token:
